import os
import logging

from ase import Atoms
from ase.io import read
from ase.io.vasp import write_vasp

from calcflow import CalculationError


# INCAR parameters that are not written to INCAR (handled separately)
_NON_INCAR_KEYS = {"pp", "kpts", "GGA"}


def _write_poscar(atoms, output_dir):
    """Write POSCAR file from ASE atoms object."""
    poscar_path = os.path.join(output_dir, "POSCAR")
    write_vasp(poscar_path, atoms, direct=True, sort=True)
    print("    POSCAR written")
    logging.info("POSCAR written to %s", poscar_path)


def _write_incar(params, output_dir):
    """Write INCAR file from parameter dict."""
    incar_path = os.path.join(output_dir, "INCAR")
    with open(incar_path, "w", encoding="utf-8") as f:
        f.write("# INCAR generated by CalcFlow\n")
        for key in sorted(params):
            if key in _NON_INCAR_KEYS:
                continue
            val = params[key]
            if isinstance(val, bool):
                val = ".TRUE." if val else ".FALSE."
            f.write(f"{key} = {val}\n")
    print("    INCAR written")
    logging.info("INCAR written to %s", incar_path)


def _write_kpoints(params, output_dir):
    """Write KPOINTS file. Uses kpts from params or defaults to gamma-only."""
    kpoints_path = os.path.join(output_dir, "KPOINTS")
    kpts = params.get("kpts", (1, 1, 1))

    with open(kpoints_path, "w", encoding="utf-8") as f:
        f.write("Automatic mesh\n")
        f.write("0\n")
        f.write("Gamma\n")
        f.write(f"  {kpts[0]}  {kpts[1]}  {kpts[2]}\n")
        f.write("  0  0  0\n")
    print("    KPOINTS written")
    logging.info("KPOINTS written to %s", kpoints_path)


def run_vasp_calc(poscar_path, output_dir, params):
    """
    Set up a VASP calculation by writing input files.

    Writes POSCAR, INCAR, and KPOINTS to the output directory.
    POTCAR must be generated separately (e.g. via the cluster's VASP setup).

    Args:
        poscar_path: Path to the input structure file (POSCAR, CIF, XYZ, etc.)
        output_dir: Directory where VASP files will be written
        params: Dict of VASP parameters (from a preset or merged)
    """
    print("\n  Writing VASP input files...")
    try:
        atoms: Atoms = read(poscar_path, index=-1)  # type: ignore[assignment]
    except Exception as e:
        raise CalculationError(f"Failed to read structure from '{poscar_path}': {e}") from e

    try:
        _write_poscar(atoms, output_dir)
        _write_incar(params, output_dir)
        _write_kpoints(params, output_dir)
        logging.info("VASP input files written to %s", output_dir)
    except CalculationError:
        raise
    except Exception as e:
        raise CalculationError(f"Failed to write VASP input files: {e}") from e
